### ISSUE TITLE
How to use this when my UICollectionViewController is a Child of a UIViewController(Parent)?

### ISSUE THREAD

**Issue by farhan-syed** [y-hryk/YSLTransitionAnimator#2]
I have a UICollectionView and i have it as a child by having a container view in a UIViewController but the image isnt transitioning? i was thinking maybe due to becuase YSLTransitionAnimator thinks its on its own Controller? Please Help.

**Comment by chx632996066** [comment]
@farhansyed9 I have the same problem, did you solve it?
